---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  init:
    desc: Initialize pre-commit hooks
    deps: [update]
    cmds:
      - pre-commit install --install-hooks --config .ci/pre-commit/config.yaml
    preconditions:
      - {
          msg: "pre-commit is not installed. Please install pre-commit.",
          sh: "command -v pre-commit",
        }
  update:
    desc: Update pre-commit dependencies
    cmds:
      - pre-commit autoupdate --config .ci/pre-commit/config.yaml
    preconditions:
      - {
          msg: "pre-commit is not installed. Please install pre-commit.",
          sh: "command -v pre-commit",
        }
  run:
    desc: Run pre-commit
    cmds:
      - pre-commit run --config .ci/pre-commit/config.yaml
    preconditions:
      - {
          msg: "pre-commit is not installed. Please install pre-commit.",
          sh: "command -v pre-commit",
        }
  run-all:
    desc: Run all pre-commit hooks
    cmds:
      - pre-commit run --all-files --config .ci/pre-commit/config.yaml
    preconditions:
      - {
          msg: "pre-commit is not installed. Please install pre-commit.",
          sh: "command -v pre-commit",
        }
  uninstall:
    desc: Uninstall pre-commit hooks
    cmds:
      - pre-commit uninstall
    preconditions:
      - {
          msg: "pre-commit is not installed. Please install pre-commit.",
          sh: "command -v pre-commit",
        }
